#!/bin/bash
# ══════════════════════════════════════════════════════════════════════════════
# IT SUPPORT SYSTEM — Automated Deploy Script
# Usage: bash deploy.sh [your-domain.com]
# Example: bash deploy.sh itsupport.mycompany.com
# ══════════════════════════════════════════════════════════════════════════════

set -e

DOMAIN=${1:-"localhost"}
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

banner() { echo -e "\n${BLUE}══════════════════════════════════════${NC}"; echo -e "${BLUE}  $1${NC}"; echo -e "${BLUE}══════════════════════════════════════${NC}\n"; }
ok()     { echo -e "${GREEN}✅  $1${NC}"; }
info()   { echo -e "${YELLOW}ℹ️   $1${NC}"; }
err()    { echo -e "${RED}❌  $1${NC}"; exit 1; }

banner "IT Support System — Auto Deploy"
echo -e "Domain: ${GREEN}$DOMAIN${NC}"
echo ""

# ── CHECK DOCKER ──────────────────────────────────────────────────────────────
banner "Step 1: Checking Prerequisites"

if ! command -v docker &> /dev/null; then
  info "Docker not found — installing..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  ok "Docker installed"
else
  ok "Docker found: $(docker --version)"
fi

if ! docker compose version &> /dev/null; then
  info "Docker Compose plugin not found — installing..."
  mkdir -p ~/.docker/cli-plugins
  curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
    -o ~/.docker/cli-plugins/docker-compose
  chmod +x ~/.docker/cli-plugins/docker-compose
  ok "Docker Compose installed"
else
  ok "Docker Compose found: $(docker compose version)"
fi

# ── GENERATE .env ─────────────────────────────────────────────────────────────
banner "Step 2: Generating Configuration"

if [ ! -f .env ]; then
  info "Creating .env file..."

  # Generate secure random values
  JWT_SECRET=$(openssl rand -hex 48 2>/dev/null || head -c 64 /dev/urandom | base64 | tr -d '=+/' | head -c 64)
  ENC_KEY=$(openssl rand -hex 16 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '=+/' | head -c 32)
  DB_PASS=$(openssl rand -hex 16 2>/dev/null || head -c 24 /dev/urandom | base64 | tr -d '=+/' | head -c 24)

  PROTOCOL="http"
  if [ "$DOMAIN" != "localhost" ]; then
    PROTOCOL="https"
  fi

  cat > .env << ENVEOF
# Auto-generated by deploy.sh on $(date)
# !! Keep this file secret — never commit to git !!

FRONTEND_URL=${PROTOCOL}://${DOMAIN}
VITE_API_URL=${PROTOCOL}://${DOMAIN}

POSTGRES_DB=itsupport
POSTGRES_USER=itsupport
POSTGRES_PASSWORD=${DB_PASS}

JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENC_KEY:0:32}

HTTP_PORT=80
HTTPS_PORT=443
NODE_ENV=production
ENVEOF

  ok ".env created with auto-generated secure values"
else
  ok ".env already exists — using existing configuration"
fi

# ── UPDATE NGINX FOR DOMAIN ───────────────────────────────────────────────────
banner "Step 3: Configuring Nginx"

if [ "$DOMAIN" != "localhost" ]; then
  sed -i "s/server_name _;/server_name $DOMAIN;/" docker/nginx-proxy.conf
  ok "Nginx configured for domain: $DOMAIN"
else
  ok "Nginx configured for localhost"
fi

# ── BUILD & START ─────────────────────────────────────────────────────────────
banner "Step 4: Building & Starting All Services"
info "This takes 3-5 minutes on first run (downloading images, building)..."
echo ""

docker compose down --remove-orphans 2>/dev/null || true
docker compose build --no-cache
docker compose up -d

ok "All containers started"

# ── WAIT FOR HEALTH ───────────────────────────────────────────────────────────
banner "Step 5: Waiting for Services to Be Ready"

info "Waiting for database..."
timeout=60
until docker compose exec -T db pg_isready -U itsupport -d itsupport &>/dev/null; do
  sleep 2
  timeout=$((timeout-2))
  if [ $timeout -le 0 ]; then err "Database failed to start"; fi
done
ok "Database ready"

info "Waiting for backend API..."
timeout=120
until curl -sf http://localhost/health &>/dev/null; do
  sleep 3
  timeout=$((timeout-3))
  if [ $timeout -le 0 ]; then
    info "Checking backend logs..."
    docker compose logs backend --tail=20
    err "Backend failed to start — check logs above"
  fi
done
ok "Backend API ready"

info "Waiting for frontend..."
timeout=60
until curl -sf http://localhost &>/dev/null; do
  sleep 2
  timeout=$((timeout-2))
  if [ $timeout -le 0 ]; then err "Frontend failed to start"; fi
done
ok "Frontend ready"

# ── SSL SETUP (if domain provided) ────────────────────────────────────────────
if [ "$DOMAIN" != "localhost" ]; then
  banner "Step 6: Setting Up SSL (HTTPS)"
  info "Getting SSL certificate for $DOMAIN..."

  # Get email for certbot
  read -p "  Enter your email for SSL certificate: " SSL_EMAIL
  if [ -n "$SSL_EMAIL" ]; then
    docker compose run --rm certbot certonly \
      --webroot -w /var/www/certbot \
      --email "$SSL_EMAIL" \
      --agree-tos --no-eff-email \
      -d "$DOMAIN"

    # Enable HTTPS in nginx config
    sed -i 's/^# //' docker/nginx-proxy.conf
    sed -i "s/yourdomain.com/$DOMAIN/g" docker/nginx-proxy.conf

    docker compose restart nginx
    ok "SSL certificate installed — site is now HTTPS"
  else
    info "Skipping SSL setup (no email provided)"
  fi
fi

# ── SHOW CREDENTIALS ──────────────────────────────────────────────────────────
banner "🎉 Deployment Complete!"

PROTOCOL="http"
if [ "$DOMAIN" != "localhost" ] && [ -n "$SSL_EMAIL" ]; then
  PROTOCOL="https"
fi

echo ""
echo -e "${GREEN}Your IT Support System is live at:${NC}"
echo -e "  🌐  ${BLUE}${PROTOCOL}://${DOMAIN}${NC}"
echo ""
echo -e "${YELLOW}Default Login Accounts:${NC}"
echo "  ┌─────────────┬──────────────────────────┬──────────┐"
echo "  │ Role        │ Email                    │ Password │"
echo "  ├─────────────┼──────────────────────────┼──────────┤"
echo "  │ Super Admin │ admin@itsupport.local    │ password │"
echo "  │ Manager     │ manager@itsupport.local  │ password │"
echo "  │ Technician  │ tech@itsupport.local     │ password │"
echo "  │ Client      │ client@itsupport.local   │ password │"
echo "  └─────────────┴──────────────────────────┴──────────┘"
echo ""
echo -e "${YELLOW}⚠  Change these passwords immediately after first login!${NC}"
echo ""
echo -e "${GREEN}First steps:${NC}"
echo "  1. Login as Super Admin"
echo "  2. Go to Site Settings → add your logo, company name"
echo "  3. Go to Users → change admin email & password"
echo "  4. Go to Clients → add your client firms"
echo "  5. Go to Plugins → activate Email/WhatsApp alerts"
echo ""
echo -e "Useful commands:"
echo "  docker compose logs -f         # View live logs"
echo "  docker compose ps              # Check status"
echo "  docker compose restart         # Restart all"
echo "  docker compose down            # Stop all"
echo ""
